- RemoveNaNDataPointsFilter

# - MaxPointCountDataPointsFilter:
#     seed: 48322134
#     maxCount: 3000

- OctreeGridDataPointsFilter:
    buildParallel: 1
    maxPointByNode: 5
    maxSizeByNode: 3
    samplingMethod: 0
  
# - SurfaceNormalDataPointsFilter:
#   knn: 8
#   maxDist: 4
#   epsilon: 3
#   keepNormals: 1
#   keepDensities: 0
#   keepEigenValues: 0
#   keepEigenVectors: 0
#   smoothNormals: 0

