# yaml
name: LidarRegistraInit

point_filter:
  name: CustomPointFilter
  use_default: false
  filter_chain:
    include: /system_config/localization_config/default_config/PointFilter/init_registra_point_filter.yaml

sampler: 
  include: /system_config/localization_config/default_config/Sampler/registra_trans_rotated_sampler.yaml
 
pre_matcher: 
  name: NullPreMatcher

matcher: 
  include: /system_config/localization_config/default_config/Matcher/init_matcher.yaml
 
evaluator: 
  include: /system_config/localization_config/default_config/Matcher/evaluator_matcher.yaml
