# Set up your streams to rtsp here.
port: "8554"
streams: # Cannot rename - must leave this as is.

  stream-yay:
    type: topic
    source: /camera_30/image_raw
    mountpoint: /back
    caps: video/x-raw,framerate=10/1,width=1920,height=1080
    bitrate: 500

