version: '3.5'
services:
  robosense-cjy:    
    image: nvidia/cudagl:v8
    #image: ghcr.io/autowarefoundation/autoware:v2
    container_name: robosense-dev-$DOCKER_USERS
    hostname: in-dev-docker
    restart: always
    pid: host
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    working_dir: /workspace
    deploy:
      resources:
       reservations:
          devices:
           - driver: nvidia
             capabilities: [gpu]
    environment:
      DISPLAY: :0
      DOCKER_USER: $DOCKER_USERS
      USER: $DOCKER_USERS
      DOCKER_USER_ID: $USER_ID
      DOCKER_GRP: $DOCKER_USERS
      DOCKER_GRP_ID: $GROUP_ID
      USE_GPU_HOST: 1
      NVIDIA_VISIBLE_DEVICES: all
      HISTFILE: /workspace/.dev_bash_history
      ROS_DOMAIN_ID: 63
      # RMW_IMPLEMENTATION: rmw_kernelsoftdds_cpp
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      # CUSTOM_ROS: humble_masp
      CUSTOM_ROS: humble
    extra_hosts:
      - in-dev-docker:127.0.0.1
    volumes:
      - /dev/null:/dev/raw1394
      - /dev:/dev
      - /media:/media
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - ${WORKSPACE_PATH}:/workspace
