#* General *#
general:
  device_id: 0
socket:
  socket_address: 192.168.1.22 #10.10.8.239   # 对于发送端为远端的IP, 对于接收端建议配置为0.0.0.0
  socket_port: 6000 #60082            # 对于发送端为远端的端口, 对于接收端为监听的端口
  socket_buffer_size: 4194304   # 默认即可
  max_msg_size: 32768           # 不允许大于63KByte,默认为32KByte
  timeout_ms: 150               # 接收超时，默认150ms
  send_control:
    send_control_enable: true          # 如果发送点云时，该选项建议开启
    send_control_thres: 262144         # 默认为256KB
    send_control_ms: 2                 # 默认为2ms,建议 <= 4
    send_control_compress_enable: true # 如果发送点云时，该选项建议开启
  receive_control:
    receive_io_parallel_enable: true      # 如果发送点云，建议开启
    receive_io_parallel_degree: 4         # 根据机器设备配置，例如4核,建议配置不超过4
    receive_process_parallel_enable: true # 如果发送点云，建议开启
native:
  custom_method: Dtgh
  enable_upload: true # weather upload lidar perception data to server
  enable_lidar_object: true #
  enable_wgs84_object: true #
  upload_time_ms: 100 # upload lidar perception data time gap, default is lidar work cycle
  lidar_work_time_ms: 100 # lidar work time gap
  keep_alive_time_ms: 1000 # keep alive time gap
  device_time_status_ms: 1000 # device statue time gap
  device_no: "dt_device_no" #
  mec_no: "dt_mec_no" #



