streams:
  #- name: camera_1
  #  url: "/workspace/data/test5.mp4"
  - name: camera_2
    url: "rtsp://admin:aa123456@192.168.5.30"
  #- name: camera_3
  #  url: "rtsp://username:password@ip_address:port/stream3"
