rois:
  - index: 1
    roi_type: 0
    filter_type: 0
    anchors:
      -
        - -5.480887
        - 6.24353
        - 0
      -
        - 3.660781
        - 3.694412
        - 0
      -
        - 9.855202
        - -8.709906
        - 0
      -
        - -5.610118
        - -9.283842
        - 0
      -
        - -8.505663
        - -3.239392
        - 0
      -
        - -20.92032
        - 1.357287
        - 0
      -
        - -12.19748
        - 7.582711
        - 0
      -
        - -3.257487
        - 11.23834
        - 0
      -
        - 9.012388
        - 8.559958
        - 0
      -
        - 1.375386
        - 8.66854
        - 0