#@brief: common parameters for Odom message
common:
  msg_source: 2           #@type: int  @detail: 0--not use Odom, 1--message come from sensor driver,
                          # 2--message come from ROS, 3--message come from gnss(gnss source need setting 1)
  send_msg_ros: false     #@type: bool @detail: if true, the original Odom message will be sent out through ROS

#@brief: config file for sensor driver 
driver:
  include: /system_config/sensor_config/other_sensors/odom/odom_BYD.yaml

#@brief: configration for ROS
ros:
  ros_recv_topic: /vehv_pub
  ros_send_topic: /speed
  
